### ISSUE TITLE
Issue parsing parameters

### ISSUE THREAD

**Issue by barnettjacob** [Ironholds/urltools#15]
Hey Oliver, really nice work on this package - the `url_parameters` function and the output to data frames are awesome additions. 

Also, I just can't believe how quick the thing is - it will turn my daily url parsing job from literally hours (using httr and loops) to a few seconds work!!! 

One issue I have come up against with the `url_parameters` function - one of my parameters is 'to' (as in a dated search). The parser seems to be looking for the first instance of `to` in the whole url as being restricted to the query. The means in the url: 

`www.housetrip.es/es/buscar-apartamentos-de-vacaciones/comporta/geo?from=01/04/2015&guests=4&to=05/04/2015` 

I get `-de-vacaciones/comporta/geo?from=01/04/2015` instead of `05/04/2015`.

On this basis, I could probably also see a situation where even if it was restricted to just the query, the parser could potentially be greed about the 'to' and find it somewhere else.

Anything I can do to help just let me know - I've always got loads of URLs to parse although sadly your C++ is all greek to me at this point.

Thanks
Jacob

**Comment by Ironholds** [comment]
Yay! I mean, not yay that there's a bug, but yay that it's helpful to someone else! I wrote this because I deal with web data too, and lapply(URLdecode) made me sad :D. Glad I'm saving you some time!

On the bug; yep, good catch; it searches for <code>parameter</code>. Searching for <code>parameter + "="</code> should reduce the number of false positives and also fix this; I'll work on a patch forthwith. Any objection to me using your example in the associated unit test to prevent this happening again?

**Comment by barnettjacob** [comment]
Awesome, thanks a lot. Feel free to use the example.

**Comment by Ironholds** [comment]
Okay; it should be fixed now! To get the new version immediately:

> devtools::install_github("ironholds/urltools")

Hopefully it works better now :). Thanks so much for the feedback, and the excellent bug report - do let me know if you run into further problems!

**Comment by barnettjacob** [comment]
Brilliant, that's done it! Thank You.
